### ISSUE TITLE
sourcery failed to build swift templates with Xcode 9 beta / Swift 4

### ISSUE THREAD

**Issue by kashifshaikh** [krzysztofzablocki/Sourcery#356]
I tried just building the included templates with Sourcery, and this is the output:

```
Scanning sources...
Found "extension Encodable" of type for which there is no original type declaration information.
Found "extension Decodable" of type for which there is no original type declaration information.
Found "extension NSLock" of type for which there is no original type declaration information.
Found "extension NSRecursiveLock" of type for which there is no original type declaration information.
Found "extension UIStoryboard" of type for which there is no original type declaration information.
Found "extension UIViewController" of type for which there is no original type declaration information.
Found "extension URL" of type for which there is no original type declaration information.
Found "extension BaseMappable" of type for which there is no original type declaration information.
Found "extension Data" of type for which there is no original type declaration information.
Found "extension Dictionary" of type for which there is no original type declaration information.
Found "extension RealmSwift.List" of type for which there is no original type declaration information.
Found 151 types.
Loading templates...
Loaded 7 templates.
Generating code...
Rendering template Templates/AutoCases.stencil
error: Unknown type AutoCases, should be used with `based`
Skipping EsiMobile/Generated/AutoCases.generated.swift as it is empty.
Rendering template Templates/AutoEquatable.stencil
error: Unknown type AutoEquatable, should be used with `based`
error: Unknown type AutoEquatable, should be used with `based`
Rendering template Templates/AutoHashable.stencil
error: Unknown type AutoHashable, should be used with `based`
error: Unknown type AutoHashable, should be used with `based`
Rendering template Templates/AutoLenses.stencil
error: Unknown type AutoLenses, should be used with `based`
Rendering template Templates/AutoMockable.stencil
Rendering template Templates/Decorator.swifttemplate
/usr/bin/rsync "-av" "/usr/local/bin/Sourcery.app/Contents/Frameworks/SourceryRuntime.framework" "/var/folders/q7/pr0h22nd4cdgb2f6zrx7sg_w0000gn/T"
/usr/bin/swiftc "/var/folders/q7/pr0h22nd4cdgb2f6zrx7sg_w0000gn/T/Sourcery.build/main.swift" "-suppress-warnings" "-Onone" "-module-name" "main" "-target" "x86_64-apple-macosx10.10" "-F" "/var/folders/q7/pr0h22nd4cdgb2f6zrx7sg_w0000gn/T" "-o" "/var/folders/q7/pr0h22nd4cdgb2f6zrx7sg_w0000gn/T/Sourcery.build/bin"
error: /var/folders/q7/pr0h22nd4cdgb2f6zrx7sg_w0000gn/T/Sourcery.build/main.swift:2:8: error: module compiled with Swift 3.1 cannot be imported in Swift 4.0: /var/folders/q7/pr0h22nd4cdgb2f6zrx7sg_w0000gn/T/SourceryRuntime.framework/Modules/SourceryRuntime.swiftmodule/x86_64.swiftmodule
import SourceryRuntime
```

When I remove Decorator.swifttemplate, everything works fine.

Unfortunately if I try building sourcery in Xcode 9, I get compilation errors:
```
SWXMLHash.XMLIndexer:72:22: error: invalid redeclaration of 'Element'
    public typealias Element = SWXMLHash.XMLIndexer
                     ^
/Users/kshaikh/Github/Sourcery/Pods/SWXMLHash/Source/SWXMLHash.swift:457:10: note: 'Element' previously declared here
    case Element(XMLElement)
```

**Comment by Antondomashnev** [comment]
Hey @kashifshaikh thanks for submitting an issue, we will take a look soon on the Xcode 9 compilation issues 😄

**Comment by ilyapuchka** [comment]
This is expected. Sourcery 0.7 is still built with Xcode 8, thus it is build with Swift 3.1. The same about SourceryRuntime framework which is used internally by the tool and by Swift templates. That's why it can not be used with Xcode 9 and Swift 4. To solve that we will either need to provide a version built with Xcode 9 (we can do that and attach it to the release, will create a separate issue for that) or you need to build from sources, or not use swift templates.

P.S. if you don't use all the templates bundled with Sourcery release - don't provide its Templates folder as source of templates, specify individual templates that you need to avoid unneded code generation.
