### ISSUE TITLE
Swift templates broken in Xcode 9.3

### ISSUE THREAD

**Issue by kdawgwilk** [krzysztofzablocki/Sourcery#565]
```
Using configuration file at '.sourcery-streetyapi.yml'. WARNING: Ignoring the parameters passed in the command line.
Scanning sources...
Found 116 types.
Loading templates...
Loaded 4 templates.
Generating code...
error: Error Domain=NSOSStatusErrorDomain Code=-1 "kCFStreamErrorHTTPParseFailure / kCFSocketError / kCFStreamErrorDomainCustom / kCSIdentityUnknownAuthorityErr / qErr / telGenericError / dsNoExtsMacsBug / kMovieLoadStateError / cdevGenErr: Could not parse the request/response. /  / custom to the kind of stream in question  /  / queue element not found during deletion /  / not a SysErr, just a placeholder  /  / General error; gray cdev w/o alert" UserInfo={terminationReason=__ObjC.NSTask.TerminationReason, error=dyld: Symbol not found: __T0s11_StringCoreV22isRepresentableAsASCIISbyFSbs6UInt16VcfU_
  Referenced from: /Users/<username>/Library/Caches/Sourcery/AutoMockable.swifttemplate/../SourceryRuntime.framework/Versions/A/SourceryRuntime
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Users/<username>/Library/Caches/Sourcery/AutoMockable.swifttemplate/../SourceryRuntime.framework/Versions/A/SourceryRuntime
}
```

**Comment by kdawgwilk** [comment]
I am using the SwiftyMocky AutoMockable swifttemplate

**Comment by ilyapuchka** [comment]
For swift templates to work with Swift 4.1 it will need new release of Sourcery built with this version of Swift.

**Comment by kdawgwilk** [comment]
Any way for me to build it locally until a release happens?

**Comment by kdawgwilk** [comment]
For anyone else that comes across this my current solution is to use Xcode 9.3 but make sure I have 9.2 installed as well and set the cli tools to use 9.2 with `sudo xcode-select -s /Applications/Xcode9.2.app/Contents/Developer` so that sourcery runs using 9.2 or Swift 4.0

**Comment by Sajjon** [comment]
@ilyapuchka any idea of when an update of Sourcery with support for Xcode 9.3 is done? :)

**Comment by ilyapuchka** [comment]
It's done https://github.com/krzysztofzablocki/Sourcery/releases/tag/0.12.0

**Comment by Sajjon** [comment]
@ilyapuchka sorry, I checked yesterday then it was not done, I see it was released 14 hours ago, great timing! Thanks! :D

**Comment by kdawgwilk** [comment]
There is a regression with attributes though :( 

![screen shot 2018-04-11 at 3 49 49 pm](https://user-images.githubusercontent.com/7799267/38688563-a74ed698-3e36-11e8-8181-d1b52db87569.png)

Got some weird code like this generated using the same template after the upgrade, thankfully I was able to remove the attributes

**Comment by ilyapuchka** [comment]
@kdawgwilk please create an issue for that.

**Comment by kdawgwilk** [comment]
✅ Done. #596
