### ISSUE TITLE
Version 1.8.0 is not available in brew

### ISSUE THREAD

**Issue by iudovenko** [krzysztofzablocki/Sourcery#1054]
Hi!
It looks like your [pull request](https://github.com/Homebrew/homebrew-core/pull/97994) to brew was rejected due to failed tests.
Please fix it, we really need this update to work on Xcode 13.3

Thank you

**Comment by krzysztofzablocki** [comment]
@liamnichols any idea what we need to do for the xcodebuild failure? switching from swift build seems to be what's causing it, something related to sandbox, maybe adding explicit pathes for checkouts / derived data

**Comment by liamnichols** [comment]
Hmm interesting, I tested locally with Xcode 13.3 and all was working, but I'll take a look at the error in the PR and see what's going on

**Comment by liamnichols** [comment]
> switching from swift build seems to be what's causing it, something related to sandbox

Yep, I guess this was fine before because `swift build` was invoked with `--disable-sandbox`, which isn't available when using the `xcodebuild` command 😕 It's the same issue that is described here: https://github.com/Homebrew/discussions/discussions/59

It looks like there might be some workarounds (a fake sandbox wrapper) but nothing official has been merged back into `brew`. Maybe there are some other options though..

A bit of context for why I switched from `swift build` to `xcodebuild` in the first place from https://github.com/krzysztofzablocki/Sourcery/pull/1037#discussion_r827848589:

> So the one downside to using a static library distributed via XCFramework's is [SR-15802](https://bugs.swift.org/browse/SR-15802). `swift build`/`swift run` will work fine, but specifying `--arch x86_64 --arch arm64` will result in duplicate symbols. 
> 
> To work around this, I updated the `build` task to use `xcodebuild` instead but are you happy with this? I don't know if we need to be able to build a fat binary anywhere else? Will it cause problems elsewhere by not being able to use `swift build -c release --arch x86_64 --arch arm64`? Is it worth it? 

The important thing to note here is that this workaround was only required when building a **fat** binary (passing `--arch x86_64 --arch arm64`), which does not need to happen when using `brew install --build-from-source`, which is where the CI is failing. 

So one workaround could be to update `rake build` so that it'll use `swift build` when building a thin binary, and use `xcodebuild` for just the fat binary. 

I did consider this, but I felt it was unnecessary given that `xcodebuild` appeared to have worked 😄 Alternatively, we could follow a similar approach to SwiftLint by using `swift build` but creating the universal binary manually - https://github.com/realm/SwiftLint/blob/43c84146db4096edb97d245208fa5866f6d42223/Makefile#L71-L84

**Comment by krzysztofzablocki** [comment]
@liamnichols which approach you feel more comfortable with? we already have `fat` build as option, so you could just switch to using swift build in the `thin` version and I guess that would work again and solves issue at hand?

**Comment by liamnichols** [comment]
Yeah that is the easiest option (or even just using `swift build --disable-sandbox -c release` directly in the formulae), but tbh it would be nicer if we could avoid the inconsistency of using `xcodebuild` for fat and `swift build` for thin.

I'll see how it looks and put up a PR later today 👍

**Comment by krzysztofzablocki** [comment]
1.8.1 is in brew
