### PR TITLE
Fix AutoMockable for closure with multiple parameters

### PR DESCRIPTION
**Pull request by MontakOleg**
Resolves https://github.com/krzysztofzablocki/Sourcery/issues/1356

### CODE REVIEW

File: Templates/Templates/AutoMockable.stencil [hunk 1]
```diff
@@ -324,13 +324,11 @@ import {{ import }}
...
+{% macro methodName method %}func {{ method.shortName}}({%- for param in method.parameters %}{% if param.argumentLabel == nil %}_ {% if not param.name == "" %}{{ param.name }}{% else %}arg{{ param.index }}{% endif %}{%elif param.argumentLabel == param.name%}{{ param.name }}{%else%}{{ param.argumentLabel }} {{ param.name }}{% endif %}: {% if param.typeName.isClosure and param.typeName.closure.parameters.count > 1 %}({% endif %}{% call existentialParameterTypeName param.typeName param.isVariadic %}{% if param.typeName.isClosure and param.typeName.closure.parameters.count > 1 and not (param.typeName|contains:"any " and param.typeName.closure.returnTypeName.name|contains:"any " and param.typeName|contains:"?") %}){% endif %}{% if not forloop.last %}, {% endif %}{% endfor -%}){% endmacro %}
```
Comment (MontakOleg) [inline Templates/Templates/AutoMockable.stencil:331]: >`not (param.typeName|contains:"any " and param.typeName.closure.returnTypeName.name|contains:"any " and param.typeName|contains:"?")`

this part is needed to avoid inserting extra `)`, because it is already inserted in condition above (line 313):
```
{%- elif typeName|contains:"any " and typeName.isClosure and typeName.closure.parameters.count > 1 and typeName.closure.returnTypeName.name|contains:"any " and typeName|contains:"?" -%}
        {{ typeName | replace:"any","(any" | replace:"?",")?" | replace:") ->",")) ->" }})
```

**Comment by MontakOleg** [comment]
Linux tests failed:
>SourceryRuntime/MethodParameter_Linux.swift:25: Fatal error: unable to lookup: isOptional in MethodParameter: argumentLabel = Optional("x"), name = x, typeName = (any StubProtocol?) -> Void, `inout` = false, isVariadic = false, typeAttributes = [:], defaultValue = nil, annotations = [:], asSource = x: (any StubProtocol?) -> Void, index = 0

It looks like unrelated issue, probably introduced in https://github.com/krzysztofzablocki/Sourcery/pull/1358
